#!/bin/sh
set -e

# /etc/asterisk, /var/spool/asterisk and /var/log/asterisk are bind mounts
# from the host and start out empty (or owned by whatever UID the host has).
# Seed /etc/asterisk with the baked-in defaults on first boot, then make sure
# the asterisk user can write everywhere it needs to.

if [ -z "$(ls -A /etc/asterisk 2>/dev/null)" ]; then
    echo "[entrypoint] /etc/asterisk is empty, seeding defaults..."
    cp -a /etc/asterisk-defaults/. /etc/asterisk/
fi

# pjsip.conf / extensions.conf / voicemail.conf are generated by the webapp
# from the database. Make sure stubs exist so Asterisk can boot even before
# the webapp has run its first generation pass.
for f in pjsip.conf extensions.conf voicemail.conf; do
    if [ ! -f "/etc/asterisk/$f" ]; then
        echo "[entrypoint] no $f yet, writing empty stub"
        : > "/etc/asterisk/$f"
    fi
done

mkdir -p /var/spool/asterisk/voicemail /var/spool/asterisk/recording /var/spool/asterisk/monitor /var/spool/asterisk/ivr-prompts
mkdir -p /var/log/asterisk /var/run/asterisk

# manager.conf / cdr_pgsql.conf carry credentials from the environment —
# re-render them on every boot so .env changes take effect on restart
# without needing to rebuild the image or wipe the volume.
: "${AMI_USER:?AMI_USER is required}"
: "${AMI_SECRET:?AMI_SECRET is required}"
: "${CDR_DB_HOST:?CDR_DB_HOST is required}"
: "${CDR_DB_PORT:=5432}"
: "${CDR_DB_NAME:?CDR_DB_NAME is required}"
: "${CDR_DB_USER:?CDR_DB_USER is required}"
: "${CDR_DB_PASSWORD:?CDR_DB_PASSWORD is required}"
: "${RESEND_SMTP_HOST:=smtp.resend.com}"
: "${RESEND_SMTP_PORT:=587}"
: "${RESEND_SMTP_USER:=resend}"
: "${RESEND_SMTP_PASSWORD:=}"
: "${VOICEMAIL_FROM_EMAIL:=voicemail@localhost}"
export AMI_USER AMI_SECRET CDR_DB_HOST CDR_DB_PORT CDR_DB_NAME CDR_DB_USER CDR_DB_PASSWORD
export RESEND_SMTP_HOST RESEND_SMTP_PORT RESEND_SMTP_USER RESEND_SMTP_PASSWORD VOICEMAIL_FROM_EMAIL

envsubst < /etc/asterisk-templates/manager.conf.template > /etc/asterisk/manager.conf
envsubst < /etc/asterisk-templates/cdr_pgsql.conf.template > /etc/asterisk/cdr_pgsql.conf
envsubst < /etc/asterisk-templates/msmtprc.template > /etc/msmtprc
chmod 600 /etc/msmtprc
chown asterisk:asterisk /etc/msmtprc

chown -R asterisk:asterisk /etc/asterisk /var/spool/asterisk /var/log/asterisk /var/run/asterisk /var/lib/asterisk

exec "$@"
